pool:
 vmImage: 'ubuntu-latest'

variables:
    buildConfiguration: 'Release'

jobs:
- job: build
  displayName: 'Build and Publish NuGet Package'

  steps: 
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
     command: restore
     projects: '**/GovUkDesignSystem/GovUkDesignSystem.csproj'
     arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
     command: build
     projects: '**/GovUkDesignSystem/GovUkDesignSystem.csproj'
     arguments: '--configuration $(buildConfiguration) --no-restore'
  
  - task: DotNetCoreCLI@2
    displayName: 'Create NuGet Package'
    inputs:
      command: pack
      projects: '**/GovUkDesignSystem/GovUkDesignSystem.csproj'
      buildProperties: 'VersionSuffix="$(Build.BuildNumber)"'
      packDirectory: '$(Build.ArtifactStagingDirectory)/packages/releases'
      arguments: '--configuration $(buildConfiguration)'

  - task: NuGetCommand@2
    displayName: 'Push NuGet Package'
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/packages/releases/*.nupkg'
      publishVstsFeed: 'be9eed3c-7b4f-40e5-9a47-6fb3d3764885/a3506a0f-ba41-4b6e-bcd3-cd84d73d74b2'
      allowPackageConflicts: true